languageCode: "en-us"
baseUrl: "/"
# theme: "terminal"
paginate: 5
googleAnalytics: "UA-23906734-2"

module:
  imports:
    - path: github.com/panr/hugo-theme-terminal

params:
#  author: "Dan Clough"
  contentTypeName: "posts"
  themeColor: "blue"
  showMenuItems: 0
  fullWidthTheme: false
  centerTheme: true
  autoCover: true
  favicon: "images/favicon.ico"

languages:
  en:
    languageName: "English"
    title: "Buffer Overflow"
    subtitle: "A blog for my tech experiments and experiences"
    copyright: "All original content licensed under <a href=\"https://creativecommons.org/licenses/by-sa/4.0/legalcode\">CC BY-SA 4.0</a> unless noted otherwise."
    menuMore: "File"
    readMore: "Read more"
    readOtherPosts: "Read other posts"
    missingContentMessage: "Page not found"
    missingBackButtonLabel: "Back to home page"
    params:
      logo:
        logoText: Buffer Overflow
        logoHomeLink: /
    menu:
      main:
      - identifier: home
        name: Home
        url: /
        weight: -9
      - identifier: about
        name: About me
        url: /about
        weight: -8
      - identifier: twitter
        name: Tweets
        url: https://twitter.com/dan_clough
        weight: 3
      - identifier: mastodon
        name: Mastodon
        pre: <a rel="me" href="https://infosec.exchange/@danclough"></a>
        url: https://infosec.exchange/@danclough
        weight: 2
      - identifier: github
        name: Code
        url: https://github.com/danclough
        weight: 1
      - identifier: exit
        name: Exit
        url: https://bellard.org/jslinux/vm.html?cpu=riscv64&url=buildroot-riscv64.cfg&mem=256
        weight: 10

markup:
  goldmark:
    renderer:
      unsafe: true
