languageCode: "en-us"
baseUrl: "/"
theme: "terminal"
paginate: 5
googleAnalytics: "UA-23906734-2"

params:
#  author: "Dan Clough"
  contentTypeName: "posts"
  themeColor: "blue"
  showMenuItems: 5
  fullWidthTheme: false
  centerTheme: true
  autoCover: true
  favicon: "images/favicon.ico"

languages:
  en:
    languageName: "English"
    title: "Buffer Overflow"
    description: "A blog for my tech experiments and experiences"
    menuMore: "Show more"
    readMore: "Read more"
    readOtherPosts: "Read other posts"
    params:
      logo:
        logoText: Buffer Overflow
        logoHomeLink: /
    menu:
      main:
      - identifier: home
        name: Home
        url: /
        weight: -9
      - identifier: about
        name: About me
        url: /about
        weight: -8
      - identifier: twitter
        name: Tweets
        url: https://twitter.com/dan_clough
        weight: 2
      - identifier: github
        name: Code
        url: https://github.com/danclough
        weight: 1

#markup:
#  goldmark:
#    renderer:
#      unsafe: true
